"""empty message

Revision ID: ede150135956
Revises: 
Create Date: 2023-04-13 14:40:36.856277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede150135956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('ciclo', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('grupo', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('ciclo', sa.String(length=5), nullable=False),
    sa.Column('grupo', sa.String(length=1), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('lecture', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('a_j', sa.String(length=1), nullable=False),
    sa.Column('oh_week', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.String(length=15), nullable=False),
    sa.Column('hour', sa.String(length=6), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    op.drop_table('staff')
    op.drop_table('estudiantes')
    # ### end Alembic commands ###
